[project]
name = "accmsc"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "actipy>=3.5.0",
    "hydra-core>=1.3.2",
    "numpy>=2.2.4",
    "omegaconf>=2.3.0",
    "pandas>=2.2.3",
    "requests>=2.32.3",
    "scipy>=1.15.2",
]
