defaults:
  - _self_

  - feature_extractor/dataset: capture24
  - feature_extractor/network: harnet10_untrained
  - feature_extractor/augmentations: harnet

  - classifier/label_transform: identity
  - classifier/network: naive_mlp_small
  - classifier/dataset: applewatch
# We mount all datasets under the download path to be able to download all of them even if they are not needed for training
  - classifier/dataset@download.applewatch: applewatch
  - classifier/dataset@download.geneactiv: geneactiv
  - classifier/dataset@download.newcastle: newcastle
  - feature_extractor/dataset@download.capture24: capture24

# Can be 'download', 'train_classifier'
task: train_ssl
# Environment config
# large_files_dir: ${hydra:runtime.cwd}
large_files_dir: /cluster/scratch/aplanincic/accmsc
# ML config
normalize_data: false
train_test_split: 0.2
# Constants

# Paths
paths:
  datasets: ${large_files_dir}/data/raw
  model_checkpoints: ${large_files_dir}/checkpoints
  processed_data: ${large_files_dir}/data/processed
