defaults:
  - _self_
  - classification_dataset: applewatch
  - ssl_dataset: capture24
  
datasets_dir: ${hydra:runtime.cwd}/data/raw
task: download
lowpass_cutoff_frequency: 20
window_length: 30
normalize_data: false