defaults:
  - _self_

  # Here we can configure the settings for a feature extractor training run
  - feature_extractor/dataset: capture24
  - feature_extractor/network: harnet10_untrained
  - feature_extractor/augmentations: harnet
  - feature_extractor/ml_config: default

  # Here we can configure the settings for a classifier training run
  - classifier/label_transform: identity
  - classifier/label_transform@classifier.test_label_transform: collapse
  - classifier/network: asleep_lstm
  - classifier/dataset: applewatch
  - classifier/ml_config: default
  - feature_extractor/augmentations@classifier.backbone_augs: best_bsc
  - feature_extractor/network@classifier.backbone_network: harnet10_ukb

  # We mount all datasets under the download path to be able to download all of them even if they are not needed for training
  - classifier/dataset@download.applewatch: applewatch
  - classifier/dataset@download.geneactiv: geneactiv
  - classifier/dataset@download.newcastle: newcastle
  - feature_extractor/dataset@download.capture24: capture24

# Can be 'download', 'train_classifier', 'train_ssl'
task: train_classifier
# Environment config
# large_files_dir: ${hydra:runtime.cwd}
large_files_dir: /cluster/scratch/aplanincic/accmsc

# Paths
paths:
  datasets: ${large_files_dir}/data/raw
  trained_model_checkpoints: ${hydra:runtime.cwd}/trained_checkpoints
  model_checkpoints: ${large_files_dir}/checkpoints
  ssl_model_checkpoints: ${paths.model_checkpoints}/ssl
  classifier_model_checkpoints: ${paths.model_checkpoints}/classifier
  processed_data: ${large_files_dir}/data/processed
